config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get 'home' => 'home#index'

  get 'portfolio' => 'portfolio#index'

  get 'contact' => 'contacts#new'
  resources 'contacts', only: [:new, :create]

  get 'service' => 'service#index'

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
        :subject => "My Contact Form",
        :to => "artemgergetc@gmail.com",
        :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:notice] = 'Спасибо за ваше сообщение. Вскоре мы с вами свяжемся!'
    else
      flash.now[:error] = 'Ошибка отправки сообщения.'
      render :new
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController

  def index
  end

end

app/controllers/service_controller.rb
class ServiceController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
  def flash_class(level)
    case level
      when :notice then "alert alert-info"
      when :success then "alert alert-success"
      when :error then "alert alert-error"
      when :alert then "alert alert-error"
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/helpers/service_helper.rb
module ServiceHelper
end

app/views/contact/index.html.erb
<div class="container container-top">
  <div class="row">
    <div class="col-sm-12 text-center">
      <h2 class="section-heading">Обратная связь</h2>
      <h3 class="section-subheading text-muted">Напишите нам и мы обязательно с вами свяжемся.</h3>
      <hr>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <form name="sentMessage" id="contactForm" novalidate="">
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Ваше Имя *" id="name" required="" data-validation-required-message="Please enter your name." aria-invalid="false">
              <p class="help-block text-danger"></p>
            </div>
            <div class="form-group">
              <input type="email" class="form-control" placeholder="Ваш Email *" id="email" required="" data-validation-required-message="Please enter your email address." aria-invalid="false">
              <p class="help-block text-danger"></p>
            </div>
            <div class="form-group">
              <input type="tel" class="form-control" placeholder="Ваш Телефон *" id="phone" required="" data-validation-required-message="Please enter your phone number." aria-invalid="false">
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <textarea class="form-control" placeholder="Ваше сообщение *" id="message" required="" data-validation-required-message="Please enter a message." aria-invalid="false"></textarea>
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="clearfix"></div>
          <div class="col-lg-12 text-center">
            <div id="success"></div>
            <button type="submit" class="btn btn-contact">Отправить</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

app/views/contacts/create.html.erb
<div class="container container-top">
  <div class="row">
    <div class="col-sm-12 text-center text-orange">
      <% flash.each do |key, value| %>
        <h3><%= value %></h3>
      <% end %>
    </div>
  </div>
</div>

app/views/contacts/new.html.erb
<div class="container container-top">
  <div class="row">
    <div class="col-sm-12 text-center">
      <h2 class="section-heading">Обратная связь</h2>
      <h3 class="section-subheading text-muted">Напишите нам и мы обязательно с вами свяжемся.</h3>
      <hr>
    </div>
  </div>
  <!--
  <div class="row">
    <div class="col-sm-12">
      <form name="sentMessage" id="contactForm" novalidate="">
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Ваше Имя *" id="name" required="" data-validation-required-message="Please enter your name." aria-invalid="false">
              <p class="help-block text-danger"></p>
            </div>
            <div class="form-group">
              <input type="email" class="form-control" placeholder="Ваш Email *" id="email" required="" data-validation-required-message="Please enter your email address." aria-invalid="false">
              <p class="help-block text-danger"></p>
            </div>
            <div class="form-group">
              <input type="tel" class="form-control" placeholder="Ваш Телефон *" id="phone" required="" data-validation-required-message="Please enter your phone number." aria-invalid="false">
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <textarea class="form-control" placeholder="Ваше сообщение *" id="message" required="" data-validation-required-message="Please enter a message." aria-invalid="false"></textarea>
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="clearfix"></div>
          <div class="col-lg-12 text-center">
            <div id="success"></div>
            <button type="submit" class="btn btn-contact">Отправить</button>
          </div>
        </div>
      </form>
    </div>
  </div>
  -->

  <div class="row">
    <div class="col-sm-12">

      <%= simple_form_for @contact, :html => {:id => 'contactForm' }, :defaults => { :input_html => { :class => "form-control" } } do |f| %>
          <div class="row">
            <div class="col-sm-6">
              <div class="form-group">
                <%= f.input :name, :required => true, :placeholder => 'Ваше имя *', :error_html => { 'class' => 'alert alert-danger contact-form-alert'} %>
              </div>
              <div class="form-group">
                <%= f.input :email, :required => true, :placeholder => 'Ваш email *', :error_html => { 'class' => 'alert alert-danger contact-form-alert'} %>
              </div>
            </div>
            <div class="col-sm-6">
              <div class="form-group">
                <%= f.input :message, :as => :text, :required => true, :placeholder => 'Ваше сообщение *', :error_html => { 'class' => 'alert alert-danger contact-form-alert'} %>
              </div>
            </div>
            <div class="row">
              <div class="col-sm-12 text-center">
                <%= f.button :submit, 'Отправить', :class=> "btn btn-contact" %>
              </div>
            </div>
          </div>
      <% end %>

    </div>
  </div>

</div>

app/views/home/index.html.erb
<!--
HORIZONTAL-MENU
-->

<header class="cd-header">
  <div id="cd-logo"><a href="#0"><img src="<%= image_path('home/LOGO2.png') %>" width="130px"></a></div>
  <!--
  <nav class="cd-primary-nav">
    <ul>
      <li><a href="#0"><%= link_to 'УСЛУГИ', service_path  %></a></li>
      <li><a href="#0"><%= link_to 'ПОРТФОЛИО', portfolio_path  %></a></li>
      <li><a href="#0"><%= link_to 'ОБРАТНАЯ СВЯЗЬ', contact_path  %></a></li>
    </ul>
  </nav>
  -->
  <nav class="cd-primary-nav">
    <ul>
      <li>
        <i class="fa fa-tablet fa-2x"></i>
        <p>8 050 555 55 55</p>
      </li>
      <li>
        <i class="fa fa-envelope fa-2x"></i>
        <p>webultim@gmail.com</p>
      </li>
    </ul>
  </nav>
</header>
<section id="cd-intro">
  <div id="cd-intro-tagline">
    <h1>Создание  WEB-сайта под ключ</h1>
    <a href="#" class="cd-btn">Оформить заявку</a>
  </div> <!-- #cd-intro-tagline -->
</section> <!-- #cd-intro -->

<%= render 'layouts/nav' %>

<!-------------------------
    MAIN SLIDER


  <div class="carousel-inner">
    <div class="item active left">
      <a href="#modal-dressroom" data-toggle="modal">

        <div class="fill" style="background-image:url('http://placehold.it/1900x1080&amp;text=Slide One');"></div>
        <div class="carousel-caption">
          <h2>Caption 1</h2>
        </div>
      </a>
    </div>
    <div class="item next left">
      <a href="#modal-dressroom" data-toggle="modal">

        <div class="fill" style="background-image:url('http://placehold.it/1900x1080&amp;text=Slide Two');"></div>
        <div class="carousel-caption">
          <h2>Caption 2</h2>
        </div>
      </a>
    </div>
    <div class="item">
      <a href="#modal-dressroom" data-toggle="modal">

        <div class="fill" style="background-image:url('http://placehold.it/1900x1080&amp;text=Slide Three');"></div>
        <div class="carousel-caption">
          <h2>Caption 3</h2>
        </div>
      </a>
    </div>
  </div>


  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="glyphicon glyphicon-menu-left"></span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="glyphicon glyphicon-menu-right"></span>
  </a>

</header>

<!-------------------------
    BLOCKS

<div class="container-fluid blocks-mainpage">
  <div class="row">

    <a href="#">
      <div class="col-sm-6 block-portfolio block-hover">
        <span>
          <div class="blocks-title">
            <h2>портфолио</h2>
          </div>
        </span>
      </div>
    </a>

    <a href="#">
      <div class="col-sm-6 block-contact block-hover">
        <span>
          <div class="blocks-title">
            <h2>обратная связь</h2>
          </div>
        </span>
      </div>
    </a>

  </div>
</div>

<!-------------------------
    ABOUT US SECTION
--------------------------->
<section class="section-grey">
  <div class="container">
    <div class="row text-green">
      <div class="col-sm-12 text-center">
        <h2 class="section-heading">Что мы предлагаем</h2>
        <hr class="hr-green">
      </div>
    </div>
    <div class="row text-center">
      <div class="col-sm-4 text-green">
            <a href="#">
                    <span class="fa-stack fa-4x">
                        <i class="fa fa-circle fa-stack-2x color-green"></i>
                        <i class="fa fa-laptop fa-stack-1x fa-inverse"></i>
                    </span>

        <h4 class="service-heading">Адаптивный Дизайн</h4>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.</p>
            </a>
      </div>
      <div class="col-sm-4 text-orange">
            <a href="#">
                    <span class="fa-stack fa-4x">
                        <i class="fa fa-circle fa-stack-2x color-orange"></i>
                        <i class="fa fa-shopping-cart fa-stack-1x fa-inverse"></i>
                    </span>

        <h4 class="service-heading">Интернет Коммерция</h4>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.</p>
            </a>
      </div>
      <div class="col-sm-4 text-green">
            <a href="#">
                    <span class="fa-stack fa-4x">
                        <i class="fa fa-circle fa-stack-2x color-green"></i>
                        <i class="fa fa-line-chart fa-stack-1x fa-inverse"></i>
                    </span>

        <h4 class="service-heading">Современные Технологии</h4>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.</p>
            </a>
      </div>
    </div>
  </div>
</section>

<!-------------------------
    LAYOUT SECTION
--------------------------->
<section class="section-white">
  <div class="container">
    <div class="row">
      <div class="col-sm-6 text-center">
        <h2 class="section-heading text-orange">Создание макетов</h2>
        <hr class="hr-orange">
        <p class="section-subheading text-green">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.</p>
      </div>
      <div class="col-sm-6">
        <img class="img-responsive img-centered" src="<%= image_path('home/maket.jpg') %>" alt="Макет" class="img-responsive">
      </div>
    </div>
  </div>
</section>

<!-------------------------
    FRONTEND SECTION
--------------------------->
<section class="section-grey">
  <div class="container">
    <div class="row">
      <div class="col-sm-8">
        <img src="<%= image_path('home/responsive.svg') %>" class="img-responsive">
      </div>
      <div class="col-sm-4">
        <h1 class="text-center text-green">Frontend</h1>
        <hr class="hr-green">
        <!--<div class="frontend-blocks">
          <a href="#">
              <img class="img-responsive img-centered" src="<%= image_path('home/frontend-pc.png') %>">
              <h4 class="text-center text-orange">ПК</h4>
          </a>
        </div>
        <div class="frontend-blocks">
          <a href="#">
              <img class="img-responsive img-centered" src="<%= image_path('home/frontend-tablet.png') %>">
              <h4 class="text-center text-green">Планшеты</h4>
          </a>
        </div>
        <div class="frontend-blocks">
          <a href="#">
              <img class="img-responsive img-centered" src="<%= image_path('home/frontend-mobile.png') %>">
              <h4 class="text-center text-green">Мобильные<br>устройства</h4>
          </a>
        </div>-->
      </div>
    </div>
  </div>
</section>

<!-------------------------
    BACKEND SECTION
--------------------------->
<section class="section-green">
  <div class="container">
    <div class="row">

      <div class="col-sm-4 col-md-4 text-center text-white">
        <h1>Backend</h1>
        <hr class="hr-white">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.</p>
      </div>
      <div class="col-sm-8 col-md-8">
        <img src="<%= image_path('home/developing-apps.jpg') %>" class="img-responsive" width="700px">
      </div>
    </div>
  </div>
</section>

<!-------------------------
    SEO SECTION
--------------------------->
<section class="section-white">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 text-orange">
        <h1 class="text-center">Search Engine Optimization</h1>
        <hr class="hr-orange">
      </div>
    </div>
    <div class="row text-green box">
      <div class="col-sm-12">
        <p class="text-center">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.</p>
      </div>
    </div>
    <div class="row box">
      <div class="col-sm-4 text-green">
        <p class="text-center">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.</p>
      </div>
      <div class="col-sm-8">
        <img class="img-responsive img-centered" src="<%= image_path('home/seographic.png') %>">
      </div>
    </div>
  </div>
</section>

<!-------------------------
    CONTACT SECTION
--------------------------->
<section class="section-grey">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 text-center">
        <h2 class="text-center text-green">Напишите нам и мы обязательно с вами свяжемся</h2>
        <a href="<%= contact_path %>"><button class="btn btn-order">Заказать сайт в один клик</button></a>
      </div>
    </div>
  </div>
</section>

app/views/layouts/_nav.erb
<!--<div class="navbar-header">
  <a class="navbar-collapsed-brand" href="<%= home_path %>">
    <img src="<%= image_path('home/LOGO2.png') %>" width="130px">
  </a>
  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-navbar-collapse">
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
</div>

<nav class="navbar-collapse collapse sidebar-navbar-collapse navbar-fixed-top">
  <div class="container" >
    <a class="navbar-brand" href="<%= home_path %>">
      <img src="<%= image_path('home/LOGO2.png') %>">
    </a>
    <ul class="nav nav-justified">
      <li><%= link_to 'Услуги', service_path  %></li>
      <li><%= link_to 'Портфолио', portfolio_path  %></li>
      <li><%= link_to 'Обратная связь', contact_path  %></li>
    </ul>
  </div>
</nav>-->

<div class="cd-secondary-nav">
  <a href="#0" class="cd-secondary-nav-trigger">Menu<span></span></a> <!-- button visible on small devices -->
  <nav>
    <ul>
      <li>
        <a href="<%= service_url %>">
          <b>Услуги</b>
        </a>
      </li>
      <li>
        <a href="<%= portfolio_url %>">
          <b>Портфолио</b>
        </a>
      </li>
      <li>
        <a href="<%= contact_url %>">
          <b>Обратная связь</b>
        </a>
      </li>
    </ul>
  </nav>
</div>


app/views/layouts/_portfolio_modal.html.erb
<div class="modal fade" id="modal-dressroom" tabindex="-1" role="dialog" aria-hidden="false">
<div class="modal-content">

  <div class="close-modal" data-dismiss="modal">
    <div class="lr">
      <div class="rl">
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2">
        <div class="modal-body">
          <!-- Project Details Go Here -->
          <h2>DressRoom</h2>
          <p class="item-intro text-muted">Интернет-магазин одежды.</p>
          <img class="modal-image img-responsive img-centered" src="<%= image_path('portfolio/dressroom-preview.png') %>" alt="">
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt repellat aperiam quasi sunt officia expedita beatae cupiditate, maiores repudiandae, nostrum, reiciendis facere nemo!</p>
          <p><strong>Сылка на сайт:</strong><a class="modal-link" href="https://webultim-webultim.c9.io/"> webultim-webultim.c9.io</a></p>
          <ul class="list-inline">
            <li><strong>Дата:</strong> Апрель 2015</li>
            <li><strong>Клиент:</strong> Elation</li>
            <li><strong>Категория:</strong> Разработка вебсайта</li>
          </ul>
          <!--<button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times"></i> Close Project</button>-->
        </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Webultim</title>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <%= yield :head %>

</head>
<body>

<% if !current_page?(root_path) %>
    <%= render 'layouts/nav' %>
<% end %>

    <%= yield %>

    <footer class="section-white">
      <div class="container">
        <div class="row">
          <div class="col-sm-6 col-xs-12">
            <p class="text-left text-green">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.</p>
          </div>
        </div>
      </div>
    </footer>

</body>
</html>

app/views/portfolio/index.html.erb
<!-- MODAL -->
<%= render 'layouts/portfolio_modal' %>

<!--
<div class="container" style="top:50px; position: relative;">
  <div class="row">
    <div class="col-sm-12 text-center">
      <h2 class="section-heading">Портфолио</h2>
      <h3 class="section-subheading text-muted">Оцените качество разработанных нами сайтов.</h3>
      <hr>
    </div>
  </div>
  <div class="row portfolio">
    <div class="col-sm-6">
      <a href="#modal-dressroom" data-toggle="modal">
        <div class="portfolio-hover">
          <img src="<%= image_url('portfolio/dressroom-preview.png') %>" class="img-responsive">
        </div>
      </a>
        <div class="portfolio-caption">
          <h3><a href="#modal-dressroom" data-toggle="modal">DressRoom</a></h3>
          <p class="text-muted">Интернет-магазин одежды</p>
        </div>
    </div>
    <div class="col-sm-6">
      <a href="#modal-dressroom" data-toggle="modal">
        <div class="portfolio-hover">
          <img src="<%= image_url('portfolio/dressroom-preview.png') %>" class="img-responsive">
        </div>
      </a>
      <div class="portfolio-caption">
        <h3><a href="#modal-dressroom" data-toggle="modal">DressRoom</a></h3>
        <p class="text-muted">Интернет-магазин одежды</p>
      </div>
    </div>
  </div>
</div>
-->

<div class="container container-top">
  <div class="row">
    <div class="col-sm-12 text-center">
      <h2 class="section-heading">Портфолио</h2>
      <h3 class="section-subheading text-muted">Оцените качество разработанных нами сайтов.</h3>
      <hr>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <ul class="grid cs-style-3">
        <li>
          <figure>
            <img class="modal-image img-responsive img-centered" src="<%= image_path('portfolio/dressroom-preview.png') %>" alt="dressroom-preview">
            <figcaption>
              <h3>Dressroom</h3>
              <span>Интернет-магазин одежды</span>
              <a href="#modal-dressroom" data-toggle="modal">Подробнее</a>
            </figcaption>
          </figure>
        </li>
      </ul>
    </div>
    <div class="col-md-6">
      <ul class="grid cs-style-3">
        <li>
          <figure>
            <img class="modal-image img-responsive img-centered" src="<%= image_path('portfolio/dressroom-preview.png') %>" alt="dressroom-preview">
            <figcaption>
              <h3>Dressroom</h3>
              <span>Интернет-магазин одежды</span>
              <a href="#modal-dressroom" data-toggle="modal">Подробнее</a>
            </figcaption>
          </figure>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/service/index.html.erb
<!-- BANNER -->
<div class="container-fluid container-top">
  <div class="row">
    <div class="col-sm-12">
      <div class="service-banner">
        <span>
          <h1>Услуги создания сайтов</h1>
          <p>Поддержка и развитие ваших проектов</p>
        </span>
        <img src="<%= image_path('service/service-banner-img.png') %>">
      </div>
    </div>
  </div>
</div>

<!-- GRID -->
<div class="container service-grid">
  <div class="row">
    <div class="col-xs-1"></div>
    <div class="col-sm-2 background-white text-green">
      <img src="<%= image_path("") %>">
      <p>Интернет <br>консалтинг</p>
    </div>
    <div class="col-sm-2 background-green text-white">
      <p>Разработка <br>сайта</p>
    </div>
    <div class="col-sm-2 background-white text-green">
      <p>Редизайн</p>
    </div>
    <div class="col-sm-2 background-green text-white">
      <p>Дизайн сайта, <br>юзабилити</p>
    </div>
    <div class="col-sm-2 background-white text-green">
      <p>Комплексный <br>аудит</p>
    </div>
    <div class="col-xs-1"></div>
  </div>
  <div class="row">
    <div class="col-xs-1"></div>
    <div class="col-sm-2 background-green text-white">
      <p>Интернет <br>консалтинг</p>
    </div>
    <div class="col-sm-2 background-white text-green">
      <p>Разработка <br>сайта</p>
    </div>
    <div class="col-sm-2 background-green text-white">
      <p>Редизайн</p>
    </div>
    <div class="col-sm-2 background-white text-green">
      <p>Дизайн сайта, <br>юзабилити</p>
    </div>
    <div class="col-sm-2 background-green text-white">
      <p>Комплексный <br>аудит</p>
    </div>
    <div class="col-xs-1"></div>
  </div>
  <div class="row">
    <div class="col-xs-1"></div>
    <div class="col-sm-2 background-white text-green">
      <p>Интернет <br>консалтинг</p>
    </div>
    <div class="col-sm-2 background-green text-white">
      <p>Разработка <br>сайта</p>
    </div>
    <div class="col-sm-2 background-white text-green">
      <p>Редизайн</p>
    </div>
    <div class="col-sm-2 background-green text-white">
      <p>Дизайн сайта, <br>юзабилити</p>
    </div>
    <div class="col-sm-2 background-white text-green">
      <p>Комплексный <br>аудит</p>
    </div>
    <div class="col-xs-1"></div>
  </div>
</div>

<!-------------------------
    CONTACT SECTION
--------------------------->
<section class="section-grey">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 text-center">
        <h2 class="text-center text-green">Напишите нам и мы обязательно с вами свяжемся</h2>
        <a href="<%= contact_path %>"><button class="btn btn-order">Заказать сайт в один клик</button></a>
      </div>
    </div>
  </div>
</section>